services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    env_file:
      - .env/development/db
      - .env/development/web
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env/development/db
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  pg_data:
  redis_data:
