require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/creatures", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Creature. As you add validations to Creature, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Creature.create! valid_attributes
      get creatures_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      creature = Creature.create! valid_attributes
      get creature_url(creature)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_creature_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      creature = Creature.create! valid_attributes
      get edit_creature_url(creature)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Creature" do
        expect {
          post creatures_url, params: { creature: valid_attributes }
        }.to change(Creature, :count).by(1)
      end

      it "redirects to the created creature" do
        post creatures_url, params: { creature: valid_attributes }
        expect(response).to redirect_to(creature_url(Creature.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Creature" do
        expect {
          post creatures_url, params: { creature: invalid_attributes }
        }.to change(Creature, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post creatures_url, params: { creature: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested creature" do
        creature = Creature.create! valid_attributes
        patch creature_url(creature), params: { creature: new_attributes }
        creature.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the creature" do
        creature = Creature.create! valid_attributes
        patch creature_url(creature), params: { creature: new_attributes }
        creature.reload
        expect(response).to redirect_to(creature_url(creature))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        creature = Creature.create! valid_attributes
        patch creature_url(creature), params: { creature: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested creature" do
      creature = Creature.create! valid_attributes
      expect {
        delete creature_url(creature)
      }.to change(Creature, :count).by(-1)
    end

    it "redirects to the creatures list" do
      creature = Creature.create! valid_attributes
      delete creature_url(creature)
      expect(response).to redirect_to(creatures_url)
    end
  end
end
